# 5.0.0 -> 7.4.3 migration has different owner permissions and data structure, not supported
FROM grafana/grafana:7.4.3
#FROM grafana/grafana:5.0.0

COPY ./provisioning /etc/grafana/provisioning
COPY ./dashboards /var/lib/grafana/dashboards
